app/Http/routes.php
<?php

Route::get('', function(){
    return view('welcome');
});

// Autenticação
Route::auth();

// Admin
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin', 'as' => 'admin.'], function() {

    // Dashboard
    Route::get('', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    // Categories
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {
        Route::get('', ['as' => 'index', 'uses' => 'CategoriesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'CategoriesController@create']);
        Route::post('store', ['as' => 'store', 'uses' => 'CategoriesController@store']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CategoriesController@edit'])->where('id', '[0-9]+');
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'CategoriesController@update'])->where('id', '[0-9]+');
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CategoriesController@destroy'])->where('id', '[0-9]+');
    });

    // Posts
    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function() {
        Route::get('', ['as' => 'index', 'uses' => 'PostsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'PostsController@create']);
        Route::post('store', ['as' => 'store', 'uses' => 'PostsController@store']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'PostsController@edit'])->where('id', '[0-9]+');
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'PostsController@update'])->where('id', '[0-9]+');
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'PostsController@destroy'])->where('id', '[0-9]+');
    });

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    // protected $primaryKey = 'categoryId';

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['category_id', 'title', 'text', 'image'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function scopeJoinFull($query)
    {
        return $query->selectRaw("
                        posts.*,
                        categories.name as category
                     ")
                     ->join('categories', 'categories.id', '=', 'posts.category_id')
                     ->orderBy('posts.title');
    }

    public function scopeByCategory($query, $categoryId = null)
    {
        return ($categoryId) ? $query->where('category_id', '=', $categoryId) : $query;
    }

    public function getCreatedAtAttribute($value)
    {
        return date('d/m/Y', strtotime($value));
    }

    public function getFullNameAttribute()
    {
        return $this->title . ' ' . $this->category->name;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoriesRequest;
use App\Models\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * @var Category
     */
    private $category;

    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    public function index()
    {
        $categories = $this->category->with('posts')->get();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(CategoriesRequest $request)
    {
        $this->category->create($request->all());

        return redirect()->route('admin.categories.index')->with('msg', 'Saved!');
    }

    public function edit($id)
    {
        $category = $this->category->find($id);

        return view('admin.categories.edit', compact('category'));
    }

    public function update(CategoriesRequest $request, $id)
    {
        $this->category->find($id)->update($request->all());

        return redirect()->route('admin.categories.index')->with('msg', 'Saved!');
    }

    public function destroy($id)
    {
        $this->category->destroy($id);

        return redirect()->route('admin.categories.index')->with('msg', 'Deleted!');
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('admin.dashboard.index');
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\PostsRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Services\Admin\PostService;

class PostsController extends Controller
{
    /**
     * @var Post
     */
    private $post;
    /**
     * @var Category
     */
    private $category;
    /**
     * @var PostService
     */
    private $postService;

    public function __construct(Post $post,Category $category, PostService $postService)
    {
        $this->post = $post;
        $this->category = $category;
        $this->postService = $postService;
    }

    public function index(Request $request)
    {
        $categories = $this->category->lists('name', 'id');

        $posts = $this->post
                      ->with('category')
                      ->byCategory($request->get('category'))
                      ->paginate(1);

        /*$posts = $this->post
                      ->joinFull()
                      ->byCategory($request->get('category'))
                      ->paginate(1);*/

        return view('admin.posts.index', compact('posts', 'categories', 'request'));
    }

    public function create()
    {
        $categories = $this->category->lists('name', 'id');

        return view('admin.posts.create', compact('categories'));
    }

    public function store(PostsRequest $request)
    {
        $this->postService->store($request->all());

        return redirect()->route('admin.posts.index')->with('msg', 'Saved!');
    }

    public function edit($id)
    {
        $categories = $this->category->lists('name', 'id');

        $post = $this->post->find($id);

        return view('admin.posts.edit', compact('post', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $this->postService->update($request->all(), $id);

        return redirect()->route('admin.posts.index')->with('msg', 'Saved!');
    }

    public function destroy($id)
    {
        $this->post->destroy($id);

        return redirect()->route('admin.posts.index')->with('msg', 'Deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Categories <small>\ New</small>
                </h1>
            </div>
        </div>

        <hr>

        @include('admin.utils.errors')

        <div class="row">
            <div class="col-sm-12">

                {!! Form::open(['route' => 'admin.categories.store', 'method' => 'post']) !!}

                    @include('admin.categories.partials.form')

                {!! Form::close() !!}

            </div>
        </div>

    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Categories <small>\ Edit: {{ $category->name }}</small>
                </h1>
            </div>
        </div>

        <hr>

        @include('admin.utils.errors')

        <div class="row">
            <div class="col-sm-12">

                {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'post']) !!}

                    @include('admin.categories.partials.form')

                {!! Form::close() !!}

            </div>
        </div>

    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Categories
                    <a href="{{ route('admin.categories.create') }}" class="btn btn-primary pull-right">New Category</a>
                </h1>
            </div>
        </div>

        <hr>

        @include('admin.utils.msg')

        <div class="row">
            <div class="col-sm-12">

                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Posts Count</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($categories as $c)
                            <tr>
                                <td width="1">{{ $c->id }}</td>
                                <td>{{ $c->name }}</td>
                                <td>{{ $c->posts->count() }}</td>
                                <td width="130">
                                    <a href="{{ route('admin.categories.edit', $c->id) }}" class="btn btn-sm btn-default">Edit</a>
                                    <a href="{{ route('admin.categories.destroy', $c->id) }}" class="btn btn-sm btn-danger">Remove</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">No results</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>

            </div>
        </div>

    </div>
@endsection

resources/views/admin/categories/partials/form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
    <a href="{{ route('admin.categories.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/dashboard/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Dashboard
                </h1>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    <script src="{{ asset('assets/admin/js/modules/dashboard/index.js') }}"></script>
@endsection

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Posts <small>\ New</small>
                </h1>
            </div>
        </div>

        <hr>

        @include('admin.utils.errors')

        <div class="row">
            <div class="col-sm-12">

                {!! Form::open(['route' => 'admin.posts.store', 'method' => 'post']) !!}

                    @include('admin.posts.partials.form')

                {!! Form::close() !!}

            </div>
        </div>

    </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Posts <small>\ Edit: {{ $post->title }}</small>
                </h1>
            </div>
        </div>

        <hr>

        @include('admin.utils.errors')

        <div class="row">
            <div class="col-sm-12">

                {!! Form::model($post, ['route' => ['admin.posts.update', $post->id], 'method' => 'post']) !!}

                    @include('admin.posts.partials.form')

                {!! Form::close() !!}

            </div>
        </div>

    </div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Posts
                    <a href="{{ route('admin.posts.create') }}" class="btn btn-primary pull-right">New Post</a>
                </h1>
            </div>
        </div>

        <hr>

        {!! Form::open(['route' => 'admin.posts.index', 'method' => 'get']) !!}
        <div class="well well-sm">
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::select('category', $categories, $request->get('category'), ['class' => 'form-control']) !!}
                </div>
                <div class="col-sm-6">
                    {!! Form::submit('Search', ['class' => 'btn btn-primary']) !!}
                </div>
            </div>
        </div>
        {!! Form::close() !!}

        @include('admin.utils.msg')

        <div class="row">
            <div class="col-sm-12">

                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($posts as $p)
                            <tr>
                                <td width="1">{{ $p->id }}</td>
                                {{--<td>{{ $p->full_name }}</td>--}}
                                <td>{{ $p->title }}</td>
                                <td>{{ $p->category->name }}</td>
                                <td>{{ $p->created_at }}</td>
                                <td width="130">
                                    <a href="{{ route('admin.posts.edit', $p->id) }}" class="btn btn-sm btn-default">Edit</a>
                                    <a href="{{ route('admin.posts.destroy', $p->id) }}" class="btn btn-sm btn-danger">Remove</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">No results</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>

                {!! $posts->appends($request->all())->links() !!}

            </div>
        </div>

    </div>
@endsection

resources/views/admin/posts/partials/form.blade.php
<div class="form-group">
    {!! Form::label('category_id', 'Category') !!}
    {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('title', 'Title') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('text', 'Text') !!}
    {!! Form::textarea('text', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
    <a href="{{ route('admin.posts.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/utils/errors.blade.php
@if($errors->any())
    <ul class="alert alert-danger list-unstyled">
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

resources/views/admin/utils/msg.blade.php
@if(session('msg'))
    <p class="alert alert-success">{{ session('msg') }}</p>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>

    @yield('styles')

</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    @if (!Auth::guest())
                        <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                        <li><a href="{{ route('admin.categories.index') }}">Categories</a></li>
                        <li><a href="{{ route('admin.posts.index') }}">Posts</a></li>
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

    @yield('scripts')

</body>
</html>